### ISSUE TITLE
:dexDebug Error with PushWoosh plugin

### ISSUE THREAD

**Issue by peek4y** [EddyVerbruggen/cordova-plugin-googleplus#101]
Having issues with GooglePlus plugin along with PushWoosh, also I had the similar issue with PushPlugin and FacebookConnect plugin, that got resolved.

and now GooglePlus plugin doesn't build with PushWoosh plugin.

PS: Pushwoosh plugin works fine with FacebookConnect plugin and other plugins as well.

**Logs:**
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileLint
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:copyDebugLint UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:preBuild
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:preDebugBuild
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:checkDebugManifest
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:preDebugTestBuild
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:preReleaseBuild
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:prepareComAndroidSupportSupportV42000Library
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:prepareDebugDependencies
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileDebugAidl
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileDebugRenderscript
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateDebugBuildConfig
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateDebugAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeDebugAssets
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateDebugResValues
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateDebugResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeDebugResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processDebugManifest
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processDebugResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateDebugSources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:extractDebugAnnotations
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeDebugProguardFiles
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processDebugJavaRes UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageDebugJar
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileDebugNdk
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageDebugJniLibs UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageDebugLocalJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageDebugRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageDebugResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:bundleDebug
:prepareAndroidComPhonegapPluginsFacebookconnectGrabonFacebookLibUnspecifiedDebugLibrary
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preReleaseBuild
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:copyReleaseLint UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:checkReleaseManifest
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:prepareReleaseDependencies
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileReleaseAidl
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileReleaseRenderscript
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateReleaseBuildConfig
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateReleaseAssets UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeReleaseAssets
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateReleaseResValues
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateReleaseResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeReleaseResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processReleaseManifest
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processReleaseResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:generateReleaseSources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:extractReleaseAnnotations
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:mergeReleaseProguardFiles
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:processReleaseJavaRes UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageReleaseJar
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:compileReleaseNdk
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageReleaseJniLibs UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageReleaseLocalJar UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageReleaseRenderscript UP-TO-DATE
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:packageReleaseResources
:com.phonegap.plugins.facebookconnect:grabon-FacebookLib:bundleRelease
:prepareComAndroidSupportSupportV42300Library
:prepareComGoogleAndroidGmsPlayServicesBase780Library
:prepareComGoogleAndroidGmsPlayServicesGcm780Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:preDexDebug
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/home/gautham/Android/Sdk/build-tools/22.0.1/dx --dex --no-optimize --output /home/gautham/Work/grabon/grabon.app/platforms/android/build/intermediates/dex/debug --input-list=/home/gautham/Work/grabon/grabon.app/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
  	

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.76 secs

/home/gautham/Work/grabon/grabon.app/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/gautham/Work/grabon/grabon.app/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/gautham/Work/grabon/grabon.app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/gautham/Work/grabon/grabon.app/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /home/gautham/Work/grabon/grabon.app/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by cpeeyush** [comment]
I am facing the similar issue with this plugin, any solution ?

**Comment by lupus2k** [comment]
Same hare... Any solution???

**Comment by rodrigograca31** [comment]
I'm having the same issue.... 

:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugSources UP-TO-DATE
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 FAILED

BUILD FAILED

Total time: 35.403 secs

**Comment by madhumynampati** [comment]
same isssue. anybody help..
Execution failed for task ':transformClassesWithDexForDebug'.

**Comment by talbenbasat** [comment]
+1

**Comment by FarajiA** [comment]
+1

**Comment by MrDrProfX** [comment]
+1
