### ISSUE TITLE
App crashes with java.lang.IllegalStateException: GoogleApiClient must be connected.

### ISSUE THREAD

**Issue by ramirogm** [EddyVerbruggen/cordova-plugin-googleplus#133]
```java
java.lang.IllegalStateException: GoogleApiClient must be connected.
	at com.google.android.gms.common.internal.zzx.zza(Unknown Source)
	at com.google.android.gms.plus.Plus.zzf(Unknown Source)
	at com.google.android.gms.internal.zztq.getCurrentPerson(Unknown Source)
	at nl.xservices.plugins.GooglePlus.onConnected(GooglePlus.java:241)
	at com.google.android.gms.common.internal.zzl.zzj(Unknown Source)
	at com.google.android.gms.common.api.zzd.zzie(Unknown Source)
	at com.google.android.gms.common.api.zzd.zzc(Unknown Source)
	at com.google.android.gms.common.api.zzd$6.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.zzl.zzj(Unknown Source)
	at com.google.android.gms.common.internal.zzl.zzfe(Unknown Source)
	at com.google.android.gms.common.internal.zzk$zzf.zzje(Unknown Source)
	at com.google.android.gms.common.internal.zzk$zza.zzc(Unknown Source)
	at com.google.android.gms.common.internal.zzk$zza.zzi(Unknown Source)
	at com.google.android.gms.common.internal.zzk$zzc.zzjg(Unknown Source)
	at com.google.android.gms.common.internal.zzk$zzb.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5312)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

Last reported
Oct 15, 5:22 PM
Reports this week
1
Reports total
1
Application version
 
7028
1
Android version
 
Android 5.0
1
Device
 
Moto E (surnia_umts)

Last reported
Oct 15, 10:52 AM
Reports this week
2
Reports total
2
Application version
 
7028
2
Android version
 
Android 4.4
2
Device
 
MOTO E (condor_umts)

**Comment by ramirogm** [comment]
scratch that

**Comment by tehmaestro** [comment]
Hi. Did you manage to find a fix for this?

**Comment by pburgio** [comment]
Hello, I am facing the very same issue. Did you find a solution?

Cheers

**Comment by ajaybarvey** [comment]
What is the solution to this error? Error - "java.lang.IllegalStateException: Client must be connected                                                                                          at com.google.android.gms.common.internal.zzx.zza"
