### ISSUE TITLE
Plugin not compatible with Android SDK v23

### ISSUE THREAD

**Issue by aaronfranco** [EddyVerbruggen/cordova-plugin-googleplus#142]
If you are developing an App for Android SDK v23 a.k.a: Android v6, Android Marshmallow, this plugin will not work. It fails with the following error message.

````
FATAL EXCEPTION: main
    Process: com.app.package, PID: 25426
    java.lang.SecurityException: Missing android.permission.GET_ACCOUNTS
            at android.os.Parcel.readException(Parcel.java:1599)
            at android.os.Parcel.readException(Parcel.java:1552)
            at com.google.android.gms.plus.internal.zzd$zza$zza.getAccountName(Unknown Source)
            at com.google.android.gms.plus.internal.zze.getAccountName(Unknown Source)
            at com.google.android.gms.internal.zzpa.getAccountName(Unknown Source)
            at nl.xservices.plugins.GooglePlus.onConnected(GooglePlus.java:242)
            at com.google.android.gms.common.internal.zzj.zzg(Unknown Source)
            at com.google.android.gms.common.api.zze.zzmH(Unknown Source)
            at com.google.android.gms.common.api.zze.onConnected(Unknown Source)
            at com.google.android.gms.common.api.zzg$2.onConnected(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzg.zznO(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zza.zzc(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zza.zzr(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzc.zznQ(Unknown Source)
            at com.google.android.gms.common.internal.zzi$zzb.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
````
For this permission to work, it must explicitly be requested within the app while the app is running.

https://developer.android.com/training/permissions/requesting.html

**Comment by EddyVerbruggen** [comment]
Thx. I fixes for a few other plugins already - will try to find some time to fix it soon.

**Comment by aaronfranco** [comment]
Do you have the other updated plugins on Github?

**Comment by EddyVerbruggen** [comment]
Sorry missed your Q - yes I do, f.i. the last two commits here: https://github.com/Telerik-Verified-Plugins/BarcodeScanner/commits/master

**Comment by randdusing** [comment]
@aaronfranco See if this works for you: #149. I can't get my simulator working and my only Android device is 6.0, but it should work on previous versions as well. See my pull request comment for more info on cordova.hasPermission.
