### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ratancs** [EddyVerbruggen/cordova-plugin-googleplus#154]
when using with https://github.com/Wizcorp/phonegap-facebook-plugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/usr/local/Cellar/android-sdk/24.4/build-tools/23.0.2/dx --dex --no-optimize --output /Users/username/code/test/platforms/android/build/intermediates/dex/debug --input-list=/Users/username/code/test/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
  		at com.android.dx.command.dexer.Main.run(Main.java:277)
  		at com.android.dx.command.dexer.Main.main(Main.java:245)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by ratancs** [comment]
solved by adding following to build.gradle ( platform/android/) :

// GENERATED FILE! DO NOT EDIT!

apply plugin: 'android'
configurations {
   all*.exclude group: 'com.android.support', module: 'support-v4'
}

**Comment by ashishsajwan** [comment]
@ratancs can you please explain what's going on here..
which file to edit ?
& what does  // GENERATED FILE! DO NOT EDIT! mean ??

**Comment by shfaizanali** [comment]
I can't figure whats wrong and doesn't build.gradle file regenerates when we run cordova build android

**Comment by renatorroliveira** [comment]
This error really occurs, and seems like the problem is within the facebook plugin.
When you set to ignore the dependencies of support library it still works probably because the SDK included by the facebook plugin has the support lib code embedded. OMG

**Comment by renatorroliveira** [comment]
This is not a bug of this plugin, it's a problem with facebook plugin.

Alternatively, you can remove the android-support-v4.jar from the libs folder of the facebook plugin folder.
