### ISSUE TITLE
Error: 404 Not Found: cordova-plugin-googleplus

### ISSUE THREAD

**Issue by smartnisarg23** [EddyVerbruggen/cordova-plugin-googleplus#158]
I am getting plugin not found error.

`D:\Projects\wamp\www\hybridapp\cordova> cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myclientid`

It gives this output - 

`D:\Projects\wamp\www\hybridapp\cordova> cordova plugin add cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=myclientid
Fetching plugin "cordova-plugin-googleplus" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-googleplus
npm http 404 http://registry.cordova.io/cordova-plugin-googleplus
Error: 404 Not Found: cordova-plugin-googleplus
    at RegClient.<anonymous> (C:\Users\pcs227\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\n
ode_modules\npm-registry-client\lib\request.js:268:14)
    at Request.self.callback (C:\Users\pcs227\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\n
ode_modules\request\index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\pcs227\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\nod
e_modules\request\index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\pcs227\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules
\npm\node_modules\request\index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)`

**Comment by sammuggPS** [comment]
Hey @smartnisarg23,

I just merged a significant PR the other day that updated the Android side to use Google Sign-In and refactored plugin usage. The current documentation is up to date with those changes. You should check it out. 

In regards to your issue, you have two options:

1. Make sure your npm instance is set up properly. Cordova plugins are registered on and fetched from NPM. **However**, be aware that the version on npm _is not_ the most recent version of the app.
2. Add the plugin directly from GitHub! To do so, replace `cordova-plugin-googleplus` with `https://github.com/EddyVerbruggen/cordova-plugin-googleplus`. That will get you the most recent version of the plugin.

Let me know if you have any questions!

Happy Coding,
~Sam
P.S. If your issue gets resolved, please close it!
