### ISSUE TITLE
Crash after Permission

### ISSUE THREAD

**Issue by boredom2** [EddyVerbruggen/cordova-plugin-googleplus#166]
Hi there,

thanks for your great Plugin.
On android 6.0.1 and the latest Cordova (5.4.1) with a fresh install and PlayServices 8.4, the Plugin correctly asks for the Permission to manage accounts/contacts. 
The App has minSdkVersion 16 and targetSdkVersion 23 and I explicitely add in the manifest "android.permission.USE_CREDENTIALS" and "android.permission.GET_ACCOUNTS".

Anyway, as soon as I grant that right, the App crashes with the following:

12-28 08:32:45.836 25769-25769/tv.nexx.android.lab E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: tv.nexx.android.lab, PID: 25769
                                                                     java.lang.SecurityException: Missing android.permission.GET_ACCOUNTS
                                                                         at android.os.Parcel.readException(Parcel.java:1620)
                                                                         at android.os.Parcel.readException(Parcel.java:1573)
                                                                         at com.google.android.gms.plus.internal.zzd$zza$zza.getAccountName(Unknown Source)
                                                                         at com.google.android.gms.plus.internal.zze.getAccountName(Unknown Source)
                                                                         at com.google.android.gms.internal.zzqv.getAccountName(Unknown Source)
                                                                         at nl.xservices.plugins.GooglePlus.onConnected(GooglePlus.java:283)
                                                                         at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
                                                                         at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
                                                                         at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
                                                                         at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
                                                                         at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
                                                                         at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
                                                                         at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
                                                                         at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
                                                                         at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
                                                                         at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
                                                                         at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-28 08:32:46.856 25769-26281/tv.nexx.android.lab E/GAv4: Successfully bound to service but never got onServiceConnected callback

I know, that there is a similar Thread, but that one is a few months before and I am not sure, if it is really the same issue.

Thanks a lot!

**Comment by abhishekporwal** [comment]
I feel if you add a return statement after this line in requestPermissionMethod.invoke(cordova, this, REQUEST_GET_ACCOUNTS, Manifest.permission.GET_ACCOUNTS); inside method onConnected inside GooglePlus.java it will solve this problem of crashing. It worked for me.

**Comment by EddyVerbruggen** [comment]
You're right, that should be there! Can you send a PR perhaps?

**Comment by abhishekporwal** [comment]
Hello Eddy, I have already fork your code, should i commit changes there, or you want me to create a seprate PR

**Comment by EddyVerbruggen** [comment]
If you have pushed the changes to your fork then please send me a PR, should be only a few clicks. Then I'll click a few times as well and we're in sync ;)
Much appreciated!

**Comment by abhishekporwal** [comment]
Sorry i by mistake merged my changes to master, as i am new to GIT i am not fully aware of the PR process. You can review the same and if require you can revert it.

**Comment by EddyVerbruggen** [comment]
No worries, I've now created it from your fork: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/pull/171
