### ISSUE TITLE
Login and Logout multiple times crash the app

### ISSUE THREAD

**Issue by corinzio** [EddyVerbruggen/cordova-plugin-googleplus#180]
In Android logging in and out with disconnect multiple times doesn't ask for the profile selection (after the first time it never show up anymore) and often after some cycle of those operation the application crash.

here is how i call the operations:
```javascript
  executeLogin() {
    this.$window.plugins.googleplus.login(this.options, function(obj) {
      console.log("login succesful");
      this.login = obj;
      console.log(JSON.stringify(this.login));
    }.bind(this), function(msg) {
      //ERROR MESSAGE
      this.login = undefined;
      console.log('login error: ' + msg);
    }.bind(this));
  }
  executeLogout() {
    this.$window.plugins.googleplus.logout(function(msg) {
      console.log("perform logout");
      this.login = undefined;
    });
  }
```

the availability function is checked only one time when the app starts.

Here is the start of the stacktrace:

> --------- beginning of crash
02-10 11:37:46.719 21210 21210 E AndroidRuntime: FATAL EXCEPTION: main
02-10 11:37:46.719 21210 21210 E AndroidRuntime: Process: tumblr.corinzio.WineCards, PID: 21210
02-10 11:37:46.719 21210 21210 E AndroidRuntime: java.lang.IllegalStateException: GoogleApiClient must be connected.
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzx.zza(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.plus.Plus.zzf(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.internal.zzqz.getCurrentPerson(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at nl.xservices.plugins.GooglePlus.onConnected(GooglePlus.java:266)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5294)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-10 11:37:46.719 21210 21210 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: FATAL EXCEPTION: main
02-10 15:20:33.085 21363 21363 E AndroidRuntime: Process: tumblr.corinzio.WineCards, PID: 21363
02-10 15:20:33.085 21363 21363 E AndroidRuntime: java.lang.IllegalStateException: GoogleApiClient must be connected.
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzx.zza(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.plus.Plus.zzf(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.internal.zzqz.getCurrentPerson(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at nl.xservices.plugins.GooglePlus.onConnected(GooglePlus.java:266)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5294)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
02-10 15:20:33.085 21363 21363 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
--------- beginning of system

**Comment by corinzio** [comment]
no more an issue after last PR
