### ISSUE TITLE
 ~/adt-bundle-linux/sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies.

### ISSUE THREAD

**Issue by srameshr** [EddyVerbruggen/cordova-plugin-googleplus#20]
I added the plugin, and now I get this error : ~/adt-bundle-linux/sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies.

```
[dependency] Found 2 versions of android-support-v4.jar in the dependency list,
[dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
[dependency] All versions of the libraries must be the same at this time.
[dependency] Versions found are:
[dependency] Path: /home/siddharth/appTest/Madzz/ui/platforms/android/com.phonegap.plugins.facebookconnect/FacebookLib/libs/android-support-v4.jar
[dependency]    Length: 758727
[dependency]    SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
[dependency] Path: /home/siddharth/appTest/Madzz/ui/platforms/android/libs/android-support-v4.jar
[dependency]    Length: 987314
[dependency]    SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786

BUILD FAILED
/home/siddharth/Downloads/adt-bundle-linux/sdk/tools/ant/build.xml:577: Jar mismatch! Fix your dependencies

Total time: 1 second

/home/siddharth/appTest/Madzz/ui/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/siddharth/appTest/Madzz/ui/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/siddharth/appTest/Madzz/ui/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

Please have a look at this

JAR from another plugin is interrupting

**Comment by andrewb273** [comment]
It seems this plugin is using an older version of the android-support jar - I'm having to use an older version of com.phonegap.plugins.facebookconnect (v0.4.0) to avoid this dependencies issue. I can't edit the .apk as I'm using [Phonegap Build](http://build.phonegap.com). Is it possible for this android-support reference to be updated to the latest?
