### ISSUE TITLE
Latest versione errors

### ISSUE THREAD

**Issue by masai2k** [EddyVerbruggen/cordova-plugin-googleplus#212]
Hi,
I tried to install the latest version from git (not from npm), and when I execute ionic run android I received these errors:

/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:23: error: package com.google.android.gms.plus does not exist
import com.google.android.gms.plus.Plus;
                                  ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:24: error: package com.google.android.gms.plus.model.people does not exist
import com.google.android.gms.plus.model.people.Person;
                                               ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:105: error: package Plus does not exist
        Plus.AccountApi.clearDefaultAccount(mGoogleApiClient);
            ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:136: error: cannot find symbol
      this.scopes.add(Plus.SCOPE_PLUS_LOGIN);
                      ^
  symbol:   variable Plus
  location: class GooglePlus
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:137: error: cannot find symbol
      this.scopes.add(Plus.SCOPE_PLUS_PROFILE);
                      ^
  symbol:   variable Plus
  location: class GooglePlus
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:143: error: package Plus does not exist
      Plus.AccountApi.revokeAccessAndDisconnect(mGoogleApiClient)
          ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:171: error: cannot find symbol
        .addApi(Plus.API, Plus.PlusOptions.builder().build());
                ^
  symbol:   variable Plus
  location: class GooglePlus
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:171: error: package Plus does not exist
        .addApi(Plus.API, Plus.PlusOptions.builder().build());
                              ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:266: error: cannot find symbol
    final Person user = Plus.PeopleApi.getCurrentPerson(mGoogleApiClient);
          ^
  symbol:   class Person
  location: class GooglePlus
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:266: error: package Plus does not exist
    final Person user = Plus.PeopleApi.getCurrentPerson(mGoogleApiClient);
                            ^
/Applications/MAMP/htdocs/GiochiStars/platforms/android/src/nl/xservices/plugins/GooglePlus.java:284: error: package Plus does not exist
    this.email = Plus.AccountApi.getAccountName(mGoogleApiClient);
                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.741 secs
Error: Error code 1 for command: /Applications/MAMP/htdocs/giochistars/platforms/android/gradlew with args: cdvBuildDebug,-b,/Applications/MAMP/htdocs/giochistars/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true

**Comment by sammuggPS** [comment]
Hey @masai2k,

Thanks for trying out the latest version!

It looks to me like the platform itself still has the old GooglePlus.java even though you updated the plugin. Try removing the plugin from all platforms then reinstalling it.

You may be wondering why I think your platform still has the old .java. Well, mainly because we are not importing any packages for Google Plus anymore. So the lines at which many of those errors occur no longer exist in the code.

Let me know what happens!
~Sam

**Comment by masai2k** [comment]
thank you Sam! Now I can load the new version but .... with phonegap-facebook-plugin I have a new incompatibility error when I try to build my android app!!!
If I remove facebook plugin, all is ok ... but usually these two plugins have to be installed together!! Any help ???

Massimo

error:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by sammuggPS** [comment]
@masai2k,

Glad we got you one step further along! We are aware of this issue. Everytime it has come up has been when someone is using the facebook plugin, too.

Here's what I'll do. First, I'm going to close this issue. Then, I'll start a new issue thread to localize the conversation about the Dex error. I'll tag you in the first post.

Hopefully you all can figure out the problem!

**Comment by hossam9995** [comment]
+1
