### ISSUE TITLE
getting no valid token on few devices

### ISSUE THREAD

**Issue by ratancs** [EddyVerbruggen/cordova-plugin-googleplus#244]
I am getting no token found for google login where as facebook login works.

adb log says: 

I/Finsky  (25723): [2845] com.google.android.finsky.c.e.run(1151): Replicating app states via AMAS.
V/GLSActivity(25592): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
V/GLSActivity(25592): AuthDelegateWrapperCreated with selected intent: Intent { cmp=com.google.android.gms/.auth.DefaultAuthDelegateService }
E/Auth    (25592): [GoogleAccountDataServiceImpl] getToken() failed. Status BAD_AUTHENTICATION, Account: <ELLIDED:717908253>, App: com.android.vending, Service: androidsecure
E/Auth    (25592): com.google.android.gms.auth.be.account.b.d: Long live credential not available.
E/Auth    (25592): 	at com.google.android.gms.auth.be.account.b.e.a(SourceFile:105)
E/Auth    (25592): 	at com.google.android.gms.auth.be.p.a(SourceFile:355)
E/Auth    (25592): 	at com.google.android.gms.auth.be.o.a(SourceFile:260)
E/Auth    (25592): 	at com.google.android.gms.auth.firstparty.dataservice.y.a(SourceFile:197)
E/Auth    (25592): 	at com.google.android.gms.auth.firstparty.dataservice.x.a(SourceFile:558)
E/Auth    (25592): 	at com.google.android.gms.auth.firstparty.dataservice.x.a(SourceFile:196)
E/Auth    (25592): 	at com.google.android.gms.auth.o.a(SourceFile:276)
E/Auth    (25592): 	at com.google.android.gms.auth.o.a(SourceFile:196)
E/Auth    (25592): 	at com.google.android.gms.auth.o.a(SourceFile:118)
E/Auth    (25592): 	at com.google.android.b.b.onTransact(SourceFile:63)
E/Auth    (25592): 	at android.os.Binder.transact(Binder.java:361)
E/Auth    (25592): 	at com.google.android.gms.internal.o$a$a.a(Unknown Source)
E/Auth    (25592): 	at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
E/Auth    (25592): 	at com.google.android.gsf.loginservice.GoogleLoginService$AccountAuthenticatorImpl.getAuthToken(GoogleLoginService.java:302)
E/Auth    (25592): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E/Auth    (25592): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E/Auth    (25592): 	at android.os.Binder.execTransact(Binder.java:404)
E/Auth    (25592): 	at dalvik.system.NativeStart.run(Native Method)
I/Auth    (25592): [DefaultAuthDelegateService] Use browser flow? false
I/Finsky  (25723): [1] com.google.android.finsky.c.c.a(311): Completed 1 account content syncs with 0 successful.
I/Finsky  (25723): [1] com.google.android.finsky.services.j.a(156): Installation state replication failed.
I/Finsky  (25723): [1] com.google.android.finsky.services.j.a(162): Scheduling replication attempt 4.

**Comment by moni-pandey** [comment]
#
same issue : fb login works but not google
