### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define

### ISSUE THREAD

**Issue by pradeepch** [EddyVerbruggen/cordova-plugin-googleplus#343]
Hi,
I am new to cordova, When i added this plugin and run with android it is giving following error, I am using phonegap-facebook-plugin along with it then it is giving error:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

Any suggestion would be helpfull

Thanks,
Pradeep

**Comment by djett41** [comment]
sounds like you went over the 64K method limitation for a single dex process.  If you support android platform below 21, then you will need to either use progaurd rules to shrink down methods you arent using, or configure your app for multidexing, https://developer.android.com/studio/build/multidex.html.  This is unrelated to this plugin though.
