### ISSUE TITLE
Bug in GooglePlus.java Caused by java.lang.NullPointerException (With Stacktrace)

### ISSUE THREAD

**Issue by Thomasbehan** [EddyVerbruggen/cordova-plugin-googleplus#531]
Seems to be an issue with resuming from background my app auto re-logs the user in on any 401 with an invalid token this is worth looking into hopefully you guys can fix:
Error 1: `Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.[NAME].app/com.[NAME].app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=77552, result=0, data=null} to activity {com.[NAME].app/com.[NAME].app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference`

Stacktrace 1: `Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.[NAME].app/com.[NAME].app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=77552, result=0, data=null} to activity {com.[NAME].app/com.[NAME].app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3749)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3789)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2975)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:6733)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)`

Error 2:
`Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
nl.xservices.plugins.GooglePlus.handleSignInResult`
Stacktrace 2: 
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.error(java.lang.String)' on a null object reference
       at nl.xservices.plugins.GooglePlus.handleSignInResult(GooglePlus.java:322)
       at nl.xservices.plugins.GooglePlus.onActivityResult(GooglePlus.java:296)
       at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:152)
       at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:358)
       at android.app.Activity.dispatchActivityResult(Activity.java:7235)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4466)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3716)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3789)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2975)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1658)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:206)
       at android.app.ActivityThread.main(ActivityThread.java:6733)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)`

**Comment by zarelint** [comment]
![crashes](https://user-images.githubusercontent.com/5598451/65818523-7020d780-e212-11e9-9ba5-b92defb05728.png)

**Comment by zarelint** [comment]
i have this error with the .last version of plugin maybe we can wrap this error into try cath block to avoid crash app?

**Comment by mirko77** [comment]
@Thomasbehan @zarelint have you found the issue? See #440

**Comment by mirko77** [comment]
@Thomasbehan  @zarelint Also, how did you guys manage to reproduce it?

**Comment by Thomasbehan** [comment]
Hi,
Been a while since I worked on it but the environment looked like this,
Cordova 8(maybe)
Angularjs frontend inside
Then the plugin setup as the docs say

Forgot how I managed to fix it but I think it had to do with the Google API
token? 🤔

**Comment by zarelint** [comment]
Hi all, 
I din't see any more the errors with next:

```
cordova-plugin-googleplus":"8.2.0
cordova 8.1.0
```

I put a wrapper with the response to cath the errors

```
      this.googlePlusLogin().then(
          (val) => {
            return this.validateTokenMobile(val.serverAuthCode);
          },
          (err) => {
            console.log('Google plus login failed: ' + err);
            return Promise.resolve('user reject login');
          }
        );
```

**Comment by Thomasbehan** [comment]
Nice 😎

**Comment by mirko77** [comment]
> Hi all,
> I din't see any more the errors with next:
> 
> ```
> cordova-plugin-googleplus":"8.2.0
> cordova 8.1.0
> ```
> 
> I put a wrapper with the response to cath the errors
> 
> ```
>       this.googlePlusLogin().then(
>           (val) => {
>             return this.validateTokenMobile(val.serverAuthCode);
>           },
>           (err) => {
>             console.log('Google plus login failed: ' + err);
>             return Promise.resolve('user reject login');
>           }
>         );
> ```

I am experiencing #659 with `cordova-plugin-googleplus":"8.2.0`

**Comment by mirko77** [comment]
@zarelint how do you reproduce the issue? By canceling the login?

I still see the issue on the Play Console but no clue how to reproduce it myself
