### ISSUE TITLE
PhoneGap iOS build failing with V 8.0.0 +

### ISSUE THREAD

**Issue by zmilkman** [EddyVerbruggen/cordova-plugin-googleplus#657]
Not sure if this is a specific issue with just [build.phonegap.com](https://build.phonegap.com) or with the builds in general. But I have found that iOS builds **fine with version 7.0.2**, but any other version causes the iOS build to fail. 

LOG:

```
 ** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/[APP_NAME_REMOVED]/Build/Intermediates.noindex/ArchiveIntermediates/[APP_NAME_REMOVED]/IntermediateBuildFilesPath/[APP_NAME_REMOVED].build/Release-iphoneos/[APP_NAME_REMOVED].build/Objects-normal/armv7/GooglePlus.o [APP_NAME_REMOVED]/Plugins/cordova-plugin-googleplus/GooglePlus.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

Versions tested:

-  8.0.0
-  8.1.0
-  8.1.1
-  8.1.2
-  8.2.0

    <plugin name="cordova-plugin-googleplus" spec="7.0.2">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.YOUR_ID" />
    </plugin>

Using PhoneGap **cli-9.0.0**, but did try with all other versions as well.

---

Side note to help others wondering how to target a cordova-ios version:

`<preference name="phonegap-version" value="cli-9.0.0" />`

see [https://build.phonegap.com/current-support](https://build.phonegap.com/current-support) for details on version.

**Comment by alanxp** [comment]
i get this

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileAssetCatalog /Library/Developer/Xcode/DerivedData/Salestify-dwfrqjwknvdjvocsxvktsxhxzpor/Build/Intermediates.noindex/ArchiveIntermediates/Salestify/InstallationBuildProductsLocation/Applications/Salestify.app Salestify/Images.xcassets
(1 failure)
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/private/project/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

```
and its frustrating that nobody from phonegap/cordova comunity helps

**Comment by grumpygary** [comment]
I have a similar issue.  It turns out I had other plugins (Firebase, et al) accessing different versions of certain Google library pods.  I could get it to compile by removing the googleplus references from the podfile.  Unfortunately the app then crashes on startup in ios.  I think the plugin needs a version refresh in order to get things working again.

**Comment by Mahmoud-Abdelsame3** [comment]
Seems like cordova-plugin-facebook4 has been having the same issue with phonegap-build cli-9
https://github.com/jeduan/cordova-plugin-facebook4/issues/819
