### ISSUE TITLE
pod: Command failed with exit code 1

### ISSUE THREAD

**Issue by bardgr** [EddyVerbruggen/cordova-plugin-googleplus#664]
I have the following error when installing in cordova 9.0 , does anyone have something o suggest?
-----
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/user162928/Documents/titroo/titroo/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
-----

**Comment by pghoratiu** [comment]
For me it was a conflict with another plugin. Search in the plugins folder for other plugins that use GooglePlus dependencies and require an older version.
