### ISSUE TITLE
Incompatibility(conflicts) between gogle login plugin and firebase plugin

### ISSUE THREAD

**Issue by SwapnilShinde89** [EddyVerbruggen/cordova-plugin-googleplus#679]
Hi Team,

We  used outsystems to build mobile apps android and iOS both.
So we used this cordova plugin in outsystems to create plugin in outsystems and this outsystems plugin used in outsystems mobile app.

scenarios :
 - We used this plugin in our mobile app and follow the all steps using configuration guide and google login is working through my application. 
- now we added another plugin i.e firebase mobile plugin in same application. after adding this plugin google functionality is totally stopped. for cross checked i created another application with same setting but without firebase plugin it's working and with firebase not working.

we also debugged application through android studio and we got following error. 

_java.lang.NoClassDefFoundError: com.google.android.gms.auth.api.Auth
     at nl.xservices.plugins.GooglePlus.buildGoogleApiClient(GooglePlus.java:181)
     at nl.xservices.plugins.GooglePlus.execute(GooglePlus.java:88)
 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
     at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.iifl.leadapp-xzcuGtrWEIm66vMGL_jYjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.iifl.leadapp-xzcuGtrWEIm66vMGL_jYjg==/lib/arm64, /data/app/com.iifl.leadapp-xzcuGtrWEIm66vMGL_jYjg==/base.apk!/lib/arm64-v8a, /system/lib64]]_

please help me out from this issue.

**Comment by pjain168** [comment]
There is a fork created for this plugin [https://github.com/andregrillo/cordova-plugin-googleplus](https://github.com/andregrillo/cordova-plugin-googleplus)
You can try this out.
