### ISSUE TITLE
Installation is not working 

### ISSUE THREAD

**Issue by alextkd** [EddyVerbruggen/cordova-plugin-googleplus#687]
Looks like installation both with npm and github repo ref is not working.
```
Installing "cordova-plugin-googleplus" for ios
Unable to load PlatformApi from platform. Error: Cannot find module 'semver'
Failed to install 'cordova-plugin-googleplus': Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.')
    at CordovaEventEmitter.emit (events.js:187:17)
    at CordovaEventEmitter.emit (/Users/alexandrulazar/.nvm/versions/node/v10.16.1/lib/node_modules/cordova/node_modules/cordova-common/src/events.js:69:22)
    at Object.getPlatformApiFunction (/Users/alexandrulazar/.nvm/versions/node/v10.16.1/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js:384:20)
    at Object.getPlatformApi (/Users/alexandrulazar/.nvm/versions/node/v10.16.1/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js:55:32)
    at handleInstall (/Users/alexandrulazar/.nvm/versions/node/v10.16.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:580:29)
    at /Users/alexandrulazar/.nvm/versions/node/v10.16.1/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:349:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
Unhandled error. ('The platform "ios" does not appear to be a valid cordova platform. It is missing API.js. ios not supported.')```

**Comment by Karanveer-flymedia** [comment]
@alextkd - use npm i semver
then try again i think should be working

**Comment by alextkd** [comment]
Of course I figured after, but why is that not part of internal library package? I would assume this has to be dependency
