### ISSUE TITLE
java.lang.NoSuchMethodError: No static method checkHandlerThread

### ISSUE THREAD

**Issue by luboslav** [EddyVerbruggen/cordova-plugin-googleplus#725]
Hi,

whenever I try to ```logout``` or ```disconnect``` I got this error on android and app freezes.
Login works as expected.

Plugin version: 8.5.1

```
01-19 08:58:44.695  3935  4083 I GooglePlugin: Trying to logout!
01-19 08:58:44.816  3935  3935 D AndroidRuntime: Shutting down VM
01-19 08:58:44.818  3935  3935 E AndroidRuntime: FATAL EXCEPTION: main
01-19 08:58:44.818  3935  3935 E AndroidRuntime: java.lang.NoSuchMethodError: No static method checkHandlerThread(Landroid/os/Handler;Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/Preconditions; or its super classes (declaration of 'com.google.android.gms.common.internal.Preconditions' appears in /data/app/xxx-paK-2-j0brzoN1mc5_Q8Bg==/base.apk!classes3.dex)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.zaj.zaa(com.google.android.gms:play-services-base@@17.3.0:17)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zaar.zaa(com.google.android.gms:play-services-base@@17.3.0:295)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zaaf.zaf(com.google.android.gms:play-services-base@@17.3.0:130)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zaaf.zaa(com.google.android.gms:play-services-base@@17.3.0:108)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zaaz.onConnected(com.google.android.gms:play-services-base@@17.3.0:105)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zaq.onConnected(com.google.android.gms:play-services-base@@17.3.0:5)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.zah.onConnected(com.google.android.gms:play-services-base@@17.3.0:2)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$PostInitCallback.handleServiceSuccess(Unknown Source:130)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:60)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:51)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:270)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:224)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7590)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
01-19 08:58:44.818  3935  3935 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
01-19 08:58:44.824  3935  4083 W PluginManager: THREAD WARNING: exec() call to GooglePlus.logout blocked the main thread for 129ms. Plugin should use CordovaInterface.getThreadPool().
read: unexpected EOF!```

**Comment by luboslav** [comment]
Caused by other cordova-plugin.
