### ISSUE TITLE
Build Fails on iOS (GoogleSignIn is already installed and was not overwritten)

### ISSUE THREAD

**Issue by JohnDeved** [EddyVerbruggen/cordova-plugin-googleplus#728]
```
cordova-plugin-googleplus depends on GoogleSignIn, which may conflict with another plugin. GoogleSignIn@5.0.2 is already installed and was not overwritten.
Running command: pod install --verbose
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/ionic/builds/alpin11/beertastingclub-app/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
Failed to restore plugin "cordova-plugin-googleplus". You might need to try adding it again. Error: Error: pod: Command failed with exit code 1
```

works on android but fails on ios

version: 8.5.2

**Comment by nacho004** [comment]
@JohnDeved How did you solve it?
