### ISSUE TITLE
Failed to install 'cordova-plugin-googleplus':Error: 404 Not Found: cordova-plug in-googleplayservices

### ISSUE THREAD

**Issue by Asit1989** [EddyVerbruggen/cordova-plugin-googleplus#94]
Fetching plugin "https://github.com/EddyVerbruggen/cordova-plugin-googleplus" vi
a git clone
Installing "cordova-plugin-googleplus" for android
Fetching plugin "cordova-plugin-googleplayservices" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-googleplayservices
npm http 404 http://registry.cordova.io/cordova-plugin-googleplayservices
Failed to install 'cordova-plugin-googleplus':Error: 404 Not Found: cordova-plug
in-googleplayservices
    at RegClient.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\
node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-
registry-client\lib\request.js:268:14)
    at Request.self.callback (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\
node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\requ
est\index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\no
de_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\reques
t\index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roamin
g\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_module
s\request\index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Error: 404 Not Found: cordova-plugin-googleplayservices
    at RegClient.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\
node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-
registry-client\lib\request.js:268:14)
    at Request.self.callback (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\
node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\requ
est\index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roaming\npm\no
de_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\reques
t\index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\piyush.kukadiya.DGSL\AppData\Roamin
g\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_module
s\request\index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by Asit1989** [comment]
There is a plugin in cordova repository with the name com.google.play.services

**Comment by EddyVerbruggen** [comment]
There is one in npm: https://www.npmjs.com/package/cordova-plugin-googleplayservices

Are you using the latest Cordova CLI tools?

**Comment by Asit1989** [comment]
Thanks.
I updated cordova CLI to 5.0.0 and it worked
