### ISSUE TITLE
com.android.dex.DexException

### ISSUE THREAD

**Issue by Freundschaft** [EddyVerbruggen/cordova-plugin-googleplus#96]
When running cordova run android I get the following message

´´´
 	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
´´´

I assume this is due to the google play services plugin defining something thats already defined elsewhere? is there any workaround?

Thanks & Cheers

**Comment by Freundschaft** [comment]
actually rolling back to the commented out way of declaring play services dependency and deleting the cordova-play-store dependency solved the problem for me.

I understand that this causes some issues for phonegap users, right?

https://github.com/Freundschaft/cordova-plugin-googleplus/commit/b7f96da246b8cc884de234ed94da3dde2932d60e

**Comment by EddyVerbruggen** [comment]
@Freundschaft It's incompatible with build.phonegap.com, so I think a separate branch needs to be created - and use the old approach in master (the one that works for you).

Unless someone has a bright idea how to make it work in all cases.. I'm it not only depends on the cloud vs local issue, but also the cordova version (5 vs lower).

**Comment by Freundschaft** [comment]
hmhm I understand. so much pain sometimes with cordova .
I bet there is a solution somewhere but its hidden somewhere deep in the cordova docs
